### ISSUE TITLE
link to community page

### ISSUE THREAD

**Issue by cbrahms** [Appdynamics/docker-monitoring-extension#3]
Instructions link to a URL that requires a login: http://community.appdynamics.com/t5/eXchange-Community-AppDynamics/Docker-Monitoring-Extension/idi-p/14749

The community page for the Docker Monitoring Extension is 

https://www.appdynamics.com/community/exchange/extension/docker-monitoring-extension/

**Comment by BalakrishnaV** [comment]
Hi Carl,

We have corrected the links. Thanks for pointing that out.

Regards
